### ISSUE TITLE
test the new bushido calibrate activity

### ISSUE THREAD

**Issue by jovial** [fluxoid-org/CyclismoProject#26]
At the very least we need to check this works. Bonus points will be awarded for adding additional window dressing.

**Comment by jovial** [comment]
I think I forgot to shutdown the TurboService when we are done with it in the `CalibrateActivity`. We likely need a call to `TurboService#shutdown` (if the service is connected) in the Activity's onPause method (or similar). Otherwise, we leak the ant connection and won't be able to connect again without force stopping the app.

**Comment by dougszumski** [comment]
- When 40kmph is reached displays 'stop pedalling'
- When speed drops below 40kmph it asks you to speed up again

**Comment by dougszumski** [comment]
This works well enough. Sometimes you need to retry.
