### ISSUE TITLE
Bushido wiki is down

### ISSUE THREAD

**Issue by raider13** [fluxoid-org/CyclismoProject#84]
I know this is not related to the great app Cyclismo or its code. However, I think that the wiki that contains all the info and work that you have done should not be dead. I know this is not the best way to contact you, but I also know that the GIT is still active sometimes. If you can share the wiki here (or in fluxoid.org) that would be great.

Thanks you!!!

**Comment by dougszumski** [comment]
Thanks - until we fix it properly you can use this link:

http://webcache.googleusercontent.com/search?q=cache:mB3LltSbb1cJ:wiki.cowboycoders.org/wiki/Tacx_Bushido+&cd=1&hl=en&ct=clnk&gl=uk

**Comment by dougszumski** [comment]
The wiki should be up and we're planning on slowly moving it to github.

**Comment by jovial** [comment]
I've moved all the pages to https://github.com/fluxoid-org/CyclismoProject/wiki
